config/routes.rb
Rails.application.routes.draw do
  resources :heros

  get 'heros/index'
  root "heros#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:nickname, :rank, :charisma, :wisdom)
    end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/heros/_form.html.erb
<%= form_with(model: hero, local: true) do |form| %>
  <% if hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% hero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :hero_nickname %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.text_field :rank, id: :hero_rank %>
  </div>

  <div class="field">
    <%= form.label :charisma %>
    <%= form.text_field :charisma, id: :hero_charisma %>
  </div>

  <div class="field">
    <%= form.label :wisdom %>
    <%= form.text_field :wisdom, id: :hero_wisdom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/heros/edit.html.erb
<h1>Editing Hero</h1>

<%= render 'form', hero: @hero %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<p id="notice"><%= notice %></p>






<h1>Heros</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Rank</th>
      <th>Charisma</th>
      <th>Wisdom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.nickname %></td>
        <td><%= hero.rank %></td>
        <td><%= hero.charisma %></td>
        <td><%= hero.wisdom %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path %>

app/views/heros/new.html.erb
<h1>New Hero</h1>

<%= render 'form', hero: @hero %>

<%= link_to 'Back', heros_path %>

app/views/heros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @hero.nickname %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @hero.rank %>
</p>

<p>
  <strong>Charisma:</strong>
  <%= @hero.charisma %>
</p>

<p>
  <strong>Wisdom:</strong>
  <%= @hero.wisdom %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectgame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>